version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.14
  - dependency-name: "@date-io/luxon"
    versions:
    - 2.10.8
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.2
    - 5.1.3
    - 6.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.0
    - 12.8.1
    - 12.8.3
  - dependency-name: codemirror
    versions:
    - 5.59.4
  - dependency-name: workbox-navigation-preload
    versions:
    - 6.1.1
  - dependency-name: workbox-cacheable-response
    versions:
    - 6.1.1
  - dependency-name: workbox-range-requests
    versions:
    - 6.1.1
  - dependency-name: react-tooltip
    versions:
    - 4.2.13
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
  - dependency-name: workbox-broadcast-update
    versions:
    - 6.1.0
  - dependency-name: workbox-streams
    versions:
    - 6.1.0
  - dependency-name: react-scripts
    versions:
    - 4.0.2
