name: GitHub Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        steps:
          - name: Deploy to server
            uses: easingthemes/ssh-deploy@v2.2.11
            env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                SOURCE: "build/"
                REMOTE_HOST: ${{ secrets.HOST }}
                REMOTE_USER: ${{ secrets.USERNAME }}
                TARGET: ${{ secrets.REMOTE_TARGET_BLOG_CMS }}
                EXCLUDE: "/build/, /node_modules/"
